//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polimaster.Utils.DimUnits.res {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Polimaster.Utils.DimUnits.res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ALPHA {
            get {
                return ResourceManager.GetString("ALPHA", resourceCulture);
            }
        }
        
        internal static string BETA {
            get {
                return ResourceManager.GetString("BETA", resourceCulture);
            }
        }
        
        internal static string GAMMA {
            get {
                return ResourceManager.GetString("GAMMA", resourceCulture);
            }
        }
        
        internal static string MIREM {
            get {
                return ResourceManager.GetString("MIREM", resourceCulture);
            }
        }
        
        internal static string MIREM_PER_HOUR {
            get {
                return ResourceManager.GetString("MIREM_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string MIROENTGEN {
            get {
                return ResourceManager.GetString("MIROENTGEN", resourceCulture);
            }
        }
        
        internal static string MIROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("MIROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string MISIEVERT {
            get {
                return ResourceManager.GetString("MISIEVERT", resourceCulture);
            }
        }
        
        internal static string MISIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("MISIEVERT_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string MREM {
            get {
                return ResourceManager.GetString("MREM", resourceCulture);
            }
        }
        
        internal static string MREM_PER_HOUR {
            get {
                return ResourceManager.GetString("MREM_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string MROENTGEN {
            get {
                return ResourceManager.GetString("MROENTGEN", resourceCulture);
            }
        }
        
        internal static string MROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("MROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string MSIEVERT {
            get {
                return ResourceManager.GetString("MSIEVERT", resourceCulture);
            }
        }
        
        internal static string MSIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("MSIEVERT_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string REM {
            get {
                return ResourceManager.GetString("REM", resourceCulture);
            }
        }
        
        internal static string REM_PER_HOUR {
            get {
                return ResourceManager.GetString("REM_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string ROENTGEN {
            get {
                return ResourceManager.GetString("ROENTGEN", resourceCulture);
            }
        }
        
        internal static string ROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("ROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        internal static string SIEVERT {
            get {
                return ResourceManager.GetString("SIEVERT", resourceCulture);
            }
        }
        
        internal static string SIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("SIEVERT_PER_HOUR", resourceCulture);
            }
        }
    }
}
