//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polimaster.Utils.DimUnits.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polimaster.Utils.DimUnits.res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string ALPHA {
            get {
                return ResourceManager.GetString("ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string BETA {
            get {
                return ResourceManager.GetString("BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        internal static string GAMMA {
            get {
                return ResourceManager.GetString("GAMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μR.
        /// </summary>
        internal static string MICRO_ROENTGEN {
            get {
                return ResourceManager.GetString("MICRO_ROENTGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μR/h.
        /// </summary>
        internal static string MICRO_ROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("MICRO_ROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μSv.
        /// </summary>
        internal static string MICRO_SIEVERT {
            get {
                return ResourceManager.GetString("MICRO_SIEVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μSv/h.
        /// </summary>
        internal static string MICRO_SIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("MICRO_SIEVERT_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mR.
        /// </summary>
        internal static string MILLI_ROENTGEN {
            get {
                return ResourceManager.GetString("MILLI_ROENTGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mR/h.
        /// </summary>
        internal static string MILLI_ROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("MILLI_ROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mSv.
        /// </summary>
        internal static string MILLI_SIEVERT {
            get {
                return ResourceManager.GetString("MILLI_SIEVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mSv/h.
        /// </summary>
        internal static string MILLI_SIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("MILLI_SIEVERT_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nR.
        /// </summary>
        internal static string NANO_ROENTGEN {
            get {
                return ResourceManager.GetString("NANO_ROENTGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nR/h.
        /// </summary>
        internal static string NANO_ROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("NANO_ROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSv.
        /// </summary>
        internal static string NANO_SIEVERT {
            get {
                return ResourceManager.GetString("NANO_SIEVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSv/h.
        /// </summary>
        internal static string NANO_SIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("NANO_SIEVERT_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string ROENTGEN {
            get {
                return ResourceManager.GetString("ROENTGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R/h.
        /// </summary>
        internal static string ROENTGEN_PER_HOUR {
            get {
                return ResourceManager.GetString("ROENTGEN_PER_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sv.
        /// </summary>
        internal static string SIEVERT {
            get {
                return ResourceManager.GetString("SIEVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sv/h.
        /// </summary>
        internal static string SIEVERT_PER_HOUR {
            get {
                return ResourceManager.GetString("SIEVERT_PER_HOUR", resourceCulture);
            }
        }
    }
}
